### PR TITLE
[REF] odoo-peru: Camelize class in modules

### PR DESCRIPTION
**Pull request by KarenKawaii**

### CODE REVIEW

**Comment by dsabrinarg** [comment]
@KarenKawaii this change is missing https://github.com/Vauxoo/odoo-peru/blob/8.0/l10n_pe_invoice/model/invoice_conf_installer.py#L31 (this is the reason of the red on travis)

**Comment by KarenKawaii** [comment]
Ok, I'll fix it

**Comment by KarenKawaii** [comment]
oca-autopep8 command output:

```bash
~/my-modules/odoo-peru/l10n_pe_invoice/model$ oca-autopep8 -ri invoice_conf_installer.py
Traceback (most recent call last):
  File "/usr/local/bin/oca-autopep8", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/tools/autopep8_extended.py", line 188, in main
    return autopep8.main()
  File "/usr/local/lib/python2.7/dist-packages/autopep8.py", line 3622, in main
    fix_multiple_files(args.files, args, sys.stdout)
  File "/usr/local/lib/python2.7/dist-packages/autopep8.py", line 3539, in fix_multiple_files
    _fix_file((name, options, output))
  File "/usr/local/lib/python2.7/dist-packages/autopep8.py", line 3520, in _fix_file
    fix_file(*parameters)
  File "/usr/local/lib/python2.7/dist-packages/autopep8.py", line 2961, in fix_file
    fixed_source = fix_lines(fixed_source, options, filename=filename)
  File "/usr/local/lib/python2.7/dist-packages/autopep8.py", line 2941, in fix_lines
    fixed_source = fix.fix()
  File "/usr/local/lib/python2.7/dist-packages/autopep8.py", line 529, in fix
    results = _execute_pep8(pep8_options, self.source)
  File "/usr/local/lib/python2.7/dist-packages/tools/autopep8_extended.py", line 133, in _execute_pep8
    res_extended = pep8_extended_obj._execute_pep8_extendend()
  File "/usr/local/lib/python2.7/dist-packages/tools/autopep8_extended.py", line 106, in _execute_pep8_extendend
    check_results = check_method()
  File "/usr/local/lib/python2.7/dist-packages/tools/autopep8_extended.py", line 47, in check_cw0001
    parsed = ast.parse(''.join(parsed_source))
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 0
SyntaxError: encoding declaration in Unicode string
```

**Comment by KarenKawaii** [comment]
rgrep command output: clear

**Comment by KarenKawaii** [comment]
@dsabrinarg @moylop260 Rebase and green done.

**Comment by dsabrinarg** [comment]
@KarenKawaii @moylop260 :+1:  this LGTM

**Comment by moylop260** [comment]
@KarenKawaii 
Can you change manually next class name?
https://github.com/Vauxoo/odoo-peru/blob/e205b6929287f64b0e0b7ecb82deccbfbbb16eab/l10n_pe_invoice/model/invoice_conf_installer.py#L31

**Comment by dsabrinarg** [comment]
@moylop260 that manual change is already in the PR.

**Pull request merged**
